#!/usr/bin/env python
import sys
import bblib as bl

if len(sys.argv) < 4:
     sys.exit("error, usage: replaceHaltonTrans <infile> <rb> <quadon,quadoff,both>")

infile = sys.argv[1]
rb     = float(sys.argv[2])
flag   = sys.argv[3]
bl.genHaltonTrans(infile,rb,flag)
